export const ADD_CART_DATA_LOADING="ADD_CART_DATA_LOADING"
export const ADD_CART_DATA_SUCCESS="ADD_CART_DATA_SUCCESS"
export const ADD_CART_DATA_ERROR="ADD_CART_DATA_ERROR"

export const GET_CART_DATA_LOADING="GET_CART_DATA_LOADING"
export const GET_CART_DATA_SUCCESS="GET_CART_DATA_SUCCESS"
export const GET_CART_DATA_ERROR="GET_CART_DATA_ERROR"


export const EDIT_CART_DATA_LOADING="EDIT_CART_DATA_LOADING"
export const EDIT_CART_DATA_SUCCESS="EDIT_CART_DATA_SUCCESS"
export const EDIT_CART_DATA_ERROR="EDIT_CART_DATA_ERROR"


export const DELETE_CART_DATA_LOADING="DELETE_CART_DATA_LOADING"
export const DELETE_CART_DATA_SUCCESS="DELETE_CART_DATA_SUCCESS"
export const DELETE_CART_DATA_ERROR="DELETE_CART_DATA_ERROR"