
export const AUTH_SIGNUP_LOADING="AUTH_SIGNUP_LOADING"
export const AUTH_SIGNUP_SUCCESS="AUTH_SIGNUP_SUCCESS"
export const AUTH_SIGNUP_ERROR="AUTH_SIGNUP_ERROR"



export const AUTH_LOGIN_LOADING="AUTH_LOGIN_LOADING"
export const AUTH_LOGIN_SUCCESS="AUTH_LOGIN_SUCCESS"
export const AUTH_LOGIN_ERROR="AUTH_LOGIN_ERROR"

export const AUTH_LOGOUT="AUTH_LOGOUT"