

export const GET_ORDER_LOADING="GET_ORDER_LOADING"
export const GET_ORDER_SUCCESS="GET_ORDER_SUCCESS"
export const GET_ORDER_ERROR="GET_ORDER_ERROR"

export const ADD_ORDER_LOADING="ADD_ORDER_LOADING"
export const ADD_ORDER_SUCCESS="ADD_ORDER_SUCCESS"
export const ADD_ORDER_ERROR="ADD_ORDER_ERROR"

export const EDIT_ORDER_LOADING="EDIT_ORDER_LOADING"
export const EDIT_ORDER_SUCCESS="EDIT_ORDER_SUCCESS"
export const EDIT_ORDER_ERROR="EDIT_ORDER_ERROR"


export const DELETE_ORDER_LOADING="DELETE_ORDER_LOADING"
export const DELETE_ORDER_SUCCESS="DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_ERROR="DELETE_ORDER_ERROR"